# Generated by Django 3.1.3 on 2020-11-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoría')),
                ('nombreCategoria', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('idPeriodista', models.AutoField(primary_key=True, serialize=False, verbose_name='idperiodista')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('foto', models.CharField(max_length=50, verbose_name='imagen')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='email')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Imagen')),
                ('texto', models.CharField(max_length=120, verbose_name='Texto Descriptivo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Imagen')),
                ('fechaRegistro', models.DateTimeField(verbose_name='Fecha y hora de Registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.categoria')),
                ('periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.periodista')),
            ],
        ),
    ]
