# Generated by Django 3.1.3 on 2020-11-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodista',
            name='foto',
        ),
    ]
