# Generated by Django 3.1.2 on 2020-11-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_periodista_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodista',
            old_name='idPeriodista',
            new_name='idperiodista',
        ),
    ]
